version: "3.9"

services:
  app:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html/

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/

  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4t5
      MYSQL_DATABASE: test_site
      MYSQL_USER: test_site
      MYSQL_PASSWORD: password

volumes:
  mysqldata: